server:
  port: 8182
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: beca_java
    url: jdbc:mysql://ALC-67L2MH2:3306/beca_java?useTimezone=true&serverTimezone=UTC
    username: beca_java
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

prueba1:
  prueba:
    atributo: hola mundo nuevo

